#!/bin/bash

profile=$1
app_name=stack-$(echo ${profile} | head -c 1)-$2
app_version=$(aws --profile ${profile} elasticbeanstalk describe-application-versions --application-name ${app_name} | jq -r '.ApplicationVersions[0].VersionLabel')
for environ in $(aws --profile ${profile} elasticbeanstalk describe-environments --application-name ${app_name} | jq -r '.Environments[].EnvironmentName'); do
  echo -n "Redeploying ${app_name}/${app_version} to ${environ}..."
  aws --profile ${profile} elasticbeanstalk update-environment --application-name ${app_name} --environment-name ${environ} --version-label=${app_version} > /dev/null
  echo ""
done
